### PR TITLE
Add Swift implementation

### PR DESCRIPTION
**Pull request by vikgor**
Swift code added. Tested in Playgrounds

### CODE REVIEW

**Comment by kefir500** [comment]
Hi @vikgor,

Thanks a lot for your contribution!

I'm not familiar with Xcode development and Swift in particular, so:

- Are `playground.xcworkspace/` files crucial? Most of them are binaries which is not recommended for VCS. Also, I believe the `.DS_Store` file is absolutely redundant.
- Is there any chance to run the tests in Travis CI?

**Comment by vikgor** [comment]
Hi, 

- The Playgrounds is just a way to open and quickly run Swift programs. The file structure is weird, it's basically a folder with a bunch of stuff, including the actual code in /Sources/: huifier.swift and huifier_test.swift. 
I can remove everything except those two, the code is still working, however, to run the tests you'll still need to either create a Playground project or use other ways of testing it. Right now the tests are already in the Playground file, so Mac users would be able to download the whole thing and run it.
And yes, .DS_Store is useless, but it managed to get in without me noticing somehow.

- I'm not familiar with Travis CI, but the [documentation](https://docs.travis-ci.com/user/languages/objective-c/#objective-c-vs-swift) says Swift is not fully supported yet, so I'd say it either impossible or hard to make it work

**Comment by kefir500** [comment]
Here unit tests are used for continuous integration and not for running them manually.

Also, I would like to keep the structure of this repo as simple as possible (without the project and binary files, just plain scripts and classes which can be *used in other projects*) so I prefer to stick to a plain organization if you don't mind.

If Travis CI (or contributors) someday will introduce the proper way of testing Swift Playgrounds, we'll start adding the missing content, but for now I think it's better to remove the Playground files.

What do you think of the following structure?

- `swift/huifier.swift` *or*
`swift/huifier.playground/Sources/huifier.swift`
- `swift/huifier_test.swift` *or*
`swift/huifier.playground/Sources/huifier_test.swift`
- Remove the rest of the files

**Comment by vikgor** [comment]
Sure thing, I prefer keeping the file structure as simple as possible. 
This would be fine:
- `swift/huifier.swift`
- `swift/huifier_test.swift`

The rest can be removed. Once Travis CI supports Swift, I'll update the files.

**Comment by kefir500** [comment]
**Merged.** Thanks a lot for your contribution!

**Pull request merged**
